let work = Array();
work.push("Internet");
console.log(work);
work.push("KaKao");
console.log(work);
work.push("Youtube");
console.log(work);
console.log(work.pop());
console.log(work);
console.log(work.pop());
console.log(work);
console.log(work.pop());
